version: '3.5'
services:
  couchdb-node1:
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - NODENAME=couchserver1
      - ERL_FLAGS="-setcookie ${COUCHDB_COOKIE}"
    volumes:
        - ./dbdata:/opt/couchdb-node1/data